@startuml CodeOptimizer

hide circle

class CodeOptimizer {
    - inputCode: String
    - outputCode: String
    - filePath: String
    + optimizeCode(): void
    + cleanAssignments(): void
}

@enduml