@startuml SymbolTable

hide circle

class SymbolTable {
    - ArrayList<HashMap<String,ID> table 
    + addContext()
    + delContext()
    + addSymbol(ID id)
    + searchSymbol(ID id)
    + searchLocalSymbol(ID id)
    + printSymbolTable()
}

enum DataType <<enum>> {
    INT,
    DOUBLE,
    CHAR,
    VOID, 
    STRING,
    BOOLEAN
}

abstract class ID <<abstract>> {
    - String name
    - DataType dataType
    - Boolean initialized
    - Boolean used
}

class Variable {}

class Function {
    - List<DataType> args
}

SymbolTable --> ID

ID <|-- Variable
ID <|-- Function
ID --> DataType
@enduml